# Generated by Django 4.1 on 2024-05-09 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ifsc', models.CharField(max_length=256)),
                ('bank_id', models.IntegerField()),
                ('branch', models.CharField(max_length=256)),
                ('address', models.CharField(max_length=256)),
                ('city', models.CharField(max_length=256)),
                ('district', models.CharField(max_length=256)),
                ('state', models.CharField(max_length=256)),
                ('bank_name', models.CharField(max_length=256)),
            ],
        ),
    ]
